CREATE TABLESPACE SQL3_TBS
DATAFILE 'sql3_tbs.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TEMPORARY TABLESPACE SQL3_TempTBS
TEMPFILE 'sql3_temp_tbs.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 5M MAXSIZE 200M;

CREATE USER SQL3
IDENTIFIED BY sql3pass
DEFAULT TABLESPACE SQL3_TBS
TEMPORARY TABLESPACE SQL3_TempTBS
QUOTA UNLIMITED ON SQL3_TBS;

GRANT CONNECT, RESOURCE TO SQL3;
GRANT UNLIMITED TABLESPACE TO SQL3;
GRANT CREATE SESSION TO SQL3;
GRANT ALL PRIVILEGES TO SQL3;

CONNECT SQL3/sql3pass;
